spring.application.name=projectREST
security.jwt.secret=mysupersecretkey1234
security.jwt.expiration-ms=86400000   # 1 day
spring.datasource.url=jdbc:postgresql://localhost:5432/store
spring.datasource.username=postgres
spring.datasource.password=learn5
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration